DigitalStore.WebUI/Controllers/CityController.cs
using DigitalStore.Models;
using DigitalStore.Repos.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ReflectionIT.Mvc.Paging;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace DigitalStore.WebUI.Controllers
{
    [Authorize("AdminAccess")]
    public class CityController : Controller
    {
        private readonly ICityRepo _repo;
        private const int pageSize = 10;
        private const int citiesPageSize = 15;

        public CityController(ICityRepo repo)
        {
            _repo = repo;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CityList(int pageIndex = 1)
        {
            var qry = _repo.GetAll().AsQueryable().AsNoTracking().OrderBy(c => c.CityName);
            var model = PagingList.Create(qry, citiesPageSize, pageIndex);
            model.Action = nameof(CityList);
            return View(model);
        }

        public IActionResult Edit(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }

            var city = _repo.GetOne(Id);
            if (city == null)
            {
                return NotFound();
            }

            return View(city);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(City city)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _repo.Update(city);
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    ModelState.AddModelError(string.Empty,
                        $@"Unable to save the record. Another user has updated it. {ex.Message}");
                    return View(city);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, $@"Unable to save the record. {ex.Message}");
                    return View(city);
                }
                return RedirectToAction("CityList");
            }
            return View(city);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var category = _repo.GetOne(id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete([Bind("Id,Timestamp")] City city)
        {
            try
            {
                _repo.Delete(city);
            }
            catch (DbUpdateConcurrencyException ex)
            {
                ModelState.AddModelError(string.Empty,
                    $@"Unable to delete record. Another user updated the record. {ex.Message}");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $@"Unable to create record: {ex.Message}");
            }
            return RedirectToAction("CityList");
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("CityName")] City city)
        {
            ModelState.Remove("Timestamp");
            if (!ModelState.IsValid) return View(city);
            try
            {
                _repo.Add(city);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $@"Unable to create record: {ex.Message}");
                return View(city);
            }
            return RedirectToAction("CityList");
        }
    }
}

DigitalStore.WebUI/Controllers/OrderController.cs
using DigitalStore.Models;
using DigitalStore.Repos.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ReflectionIT.Mvc.Paging;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace DigitalStore.WebUI.Controllers
{
    [Authorize("AdminAccess")]
    public class OrderController : Controller
    {
        private readonly IOrderRepo _orderRepo;
        private readonly ICityRepo _cityRepo;
        private readonly ICustomerRepo _customerRepo;
        private const int orderPageSize = 15;

        public OrderController(IOrderRepo orderRepo, ICityRepo cityRepo, ICustomerRepo customerRepo)
        {
            _orderRepo = orderRepo;
            _cityRepo = cityRepo;
            _customerRepo = customerRepo;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult OrderList(int pageIndex = 1)
        {
            var qry = _orderRepo.GetRelatedData().AsQueryable().AsNoTracking().OrderBy(c => c.DeliveryDate);
            var model = PagingList.Create(qry, orderPageSize, pageIndex);
            model.Action = nameof(OrderList);
            return View(model);
        }

        public IActionResult Edit(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }

            var customer = _orderRepo.GetOne(Id);
            if (customer == null)
            {
                return NotFound();
            }

            SetCustomersAndCitiesToViewBag();
            return View(customer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Order order)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _orderRepo.Update(order);
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    ModelState.AddModelError(string.Empty,
                        $@"Unable to save the record. Another user has updated it. {ex.Message}");
                    return View(order);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, $@"Unable to save the record. {ex.Message}");
                    return View(order);
                }
                return RedirectToAction("OrderList");
            }
            return View(order);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var order = _orderRepo.GetOne(id);
            if (order == null)
            {
                return NotFound();
            }

            SetCustomersAndCitiesToViewBag();
            return View(order);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete([Bind("Id,Timestamp")] Order order)
        {
            try
            {
                _orderRepo.Delete(order);
            }
            catch (DbUpdateConcurrencyException ex)
            {
                ModelState.AddModelError(string.Empty,
                    $@"Unable to delete record. Another user updated the record. {ex.Message}");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $@"Unable to create record: {ex.Message}");
            }
            return RedirectToAction("OrderList");
        }

        public IActionResult Create()
        {
            SetCustomersAndCitiesToViewBag();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Order order)
        {
            ModelState.Remove("Timestamp");
            if (!ModelState.IsValid) return View(order);
            try
            {
                _orderRepo.Add(order);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $@"Unable to create record: {ex.Message}");
                SetCustomersAndCitiesToViewBag();
                return View(order);
            }
            return RedirectToAction("OrderList");
        }

        private void SetCustomersAndCitiesToViewBag()
        {
            ViewBag.customers = new SelectList(_customerRepo.GetAll(), "Id", "LastName");
            ViewBag.cities = new SelectList(_cityRepo.GetAll(), "Id", "CityName");
        }
    }
}

DigitalStore.WebUI/Controllers/ProductController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DigitalStore.Models;
using ReflectionIT.Mvc.Paging;
using Microsoft.AspNetCore.Mvc.Rendering;
using DigitalStore.WebUI.ExtensionClasses;
using DigitalStore.Repos.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace DigitalStore.WebUI.Controllers
{
    [Authorize("AdminAccess")]
    public class ProductController : Controller
    {
        private readonly IProductRepo _repo;
        private readonly ICategoryRepo _categoryRepo;
        private const int pageSize = 5;
        private const int productsPageSize = 15;

        public ProductController(IProductRepo repo, ICategoryRepo categoryRepo)
        {
            _repo = repo;
            _categoryRepo = categoryRepo;
        }

        [AllowAnonymous]
        public IActionResult Index(int? id, string sortOrder, string searchString, int pageIndex = 1)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.SearchString = searchString;

            var qry = _repo.Search(id).AsQueryable().AsNoTracking();

            if (!String.IsNullOrEmpty(searchString))
            {
                qry = qry.Where(q => q.ProductName.ToLower().Contains(searchString.ToLower())).AsQueryable();
            }

            qry = sortOrder switch
            {
                "Price descending" => qry.OrderByDescending(p => p.ProductPrice),
                _ => qry.OrderBy(p => p.ProductPrice),
            };

            var model = PagingList.Create(qry, pageSize, pageIndex);
            model.RouteValue = new RouteValueDictionary {
                { "searchString", searchString},
                { "sortOrder", sortOrder}
            };
            return View(model);
        }

        [AllowAnonymous]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var product = _repo.GetOne(id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        public IActionResult Create()
        {
            ViewBag.categories = new SelectList(_categoryRepo.GetAll(), "Id", "CategoryName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("ProductName,ProductPrice,ProductDescription,CategoryId")] Product product, IFormFile image)
        {
            try
            {
                product.ProductImage = ImageConvertor.ConvetrImageToByteArray(image);
                _repo.Add(product);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $@"Unable to create record: {ex.Message}");
                ViewBag.categories = new SelectList(_categoryRepo.GetAll(), "Id", "CategoryName");
                return View(product);
            }
            return RedirectToAction(nameof(ProductList));
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var inventory = _repo.GetOne(id);
            if (inventory == null)
            {
                return NotFound();
            }
            ViewBag.categories = new SelectList(_categoryRepo.GetAll(), "Id", "CategoryName");
            return View(inventory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Product product)
        {
            if (id != product.Id)
            {
                return BadRequest();
            }
            try
            {
                _repo.Update(product);
            }
            catch (DbUpdateConcurrencyException ex)
            {
                ModelState.AddModelError(string.Empty,
                    $@"Unable to save the record. Another user has updated it. {ex.Message}");
                return View(product);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $@"Unable to save the record. {ex.Message}");
                return View(product);
            }
            return RedirectToAction(nameof(ProductList));
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var inventory = _repo.GetOne(id);
            if (inventory == null)
            {
                return NotFound();
            }

            return View(inventory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete([Bind("Id,Timestamp")] Product product)
        {
            try
            {
                _repo.Delete(product);
            }
            catch (DbUpdateConcurrencyException ex)
            {
                ModelState.AddModelError(string.Empty,
                    $@"Unable to delete record. Another user updated the record. {ex.Message}");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $@"Unable to create record: {ex.Message}");
            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult ProductList(int pageIndex = 1)
        {
            var qry = _repo.GetAll().AsQueryable().AsNoTracking().OrderBy(p => p.ProductName);
            var model = PagingList.Create(qry, productsPageSize, pageIndex);

            ViewBag.categories = new SelectList(_categoryRepo.GetAll(), "Id", "CategoryName");
            model.Action = nameof(ProductList);
            return View(model);
        }
    }
}

DigitalStore.WebUI/ViewComponents/CategoryViewComponent.cs
using System.Threading.Tasks;
using DigitalStore.Repos.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace DigitalStore.WebUI.ViewComponents
{
    public class CategoryViewComponent : ViewComponent
    {
        private readonly ICategoryRepo _repo;

        public CategoryViewComponent(ICategoryRepo repo)
        {
            _repo = repo;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = _repo.GetAll().AsQueryable().OrderBy(c => c.CategoryName);
            if (categories != null)
            {
                return View("CategoryPartialView", categories);
            }
            return new ContentViewComponentResult("Unable to locate records.");
        }
    }
}

DigitalStore.WebUI/Views/Shared/_Layout.cshtml
@using DigitalStore.Models
@using DigitalStore.Repos

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] = Digital Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/DarkTheme.css"/>
    <link rel="stylesheet" href="~/css/pager.css"/>
    <link rel="stylesheet" href="~/css/home.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/NewDesign.css"/>
    <link rel="stylesheet" href="~/DigitalStore.WebUI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DigitalStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown"  asp-area="" asp-controller="Category" 
                          asp-action="Index" role="button" aria-haspopup="true" aria-expanded="false">Categories</a>
                          <div class="dropdown-menu">
                            @await Component.InvokeAsync("Category")
                           
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Separated link</a>
                          </div>
                         </li>
                    </ul>
                    <ul class="navbar-nav ">
                        <a class="nav-link" id="cartId" asp-area="" asp-controller="Cart" asp-action="Index">
                            <i class="bi bi-basket3"></i>
                        </a>
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" asp-area="" 
                              role="button" aria-haspopup="true" aria-expanded="false"><i class="bi bi-person-square"></i></a>                
                              <div class="dropdown-menu" id="shiftLeft">
                                <partial name="../Shared/Components/Login/_LoginPartial" />
                              </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    @if (!String.IsNullOrEmpty(ViewBag.isHome)){            
    <section class="mainPicture"> 
        <div class="display-main">
            <div id="onlineStore">Online store</div>
            <div id="digitalAppliances">Digital appliances</div>
            <div id="weHave">
                <p>We have a large selection of:</p>
                <p>smartphones</p>
                <p>laptops</p>
                <p>TVs</p>
            </div>
        </div>
    </section>
    }
        <div class="container">
            <main role="main" class="pb-3">
                <partial name="_Notification" />
                @RenderBody()
            </main>
        </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DigitalStore
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="module" src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DigitalStore.WebUI/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.success('@TempData["success"]');
	</script>
}

@if (TempData["error"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.success('@TempData["error"]');
	</script>
}

DigitalStore.WebUI/Views/Shared/_PersonLayout.cshtml
@using DigitalStore.Models
@using DigitalStore.Repos

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/pager.css"/>
    <link rel="stylesheet" href="~/css/DarkTheme.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/sideMenu.css"/>
    <link rel="stylesheet" href="~/css/NewDesign.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
       <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <span style="font-size: 30px; cursor: pointer" onclick="openNavmenu()"><i class="bi bi-list">Menu</i></span>  
                <a class="nav-link text-dark" id="cartId" asp-area="" asp-controller="Home" asp-action="Index">
                     Home
                </a>
            </div>
        </div>
    </nav>
    <div class="sidenavmenu" id="adminSidenavnemu">
        <a class="closebtn" href="#" onclick="closeNavmenu()">X</a>
        <br />
        <a asp-controller="Category" asp-action="CategoryList" class="btn" style="width:220px">
            Categories
        </a>
        <a asp-controller="City" asp-action="CityList" class="btn" style="width:220px">
            Cities
        </a>
        <a asp-controller="Customer" asp-action="CustomerList" class="btn" style="width:220px">
            Customers
        </a>
        <a asp-controller="Order" asp-action="OrderList" class="btn" style="width:220px">
            Orders
        </a>
        <a asp-controller="Product" asp-action="ProductList" class="btn" style="width:220px">
            Products
        </a>
        <a asp-controller="ProductOrder" asp-action="ProductOrderList" class="btn" style="width:220px">
            ProductOrders
        </a>
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DigitalStore
        </div>
    </footer>

    <script type="text/javascript" src="~/js/sideMenu.js"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>