DigitalStore.WebUI/Controllers/ProductController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DigitalStore.Models;
using ReflectionIT.Mvc.Paging;
using Microsoft.AspNetCore.Mvc.Rendering;
using DigitalStore.WebUI.ExtensionClasses;
using DigitalStore.Repos.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace DigitalStore.WebUI.Controllers
{
    [Authorize("AdminAccess")]
    public class ProductController : Controller
    {
        private readonly IProductRepo _repo;
        private readonly ICategoryRepo _categoryRepo;
        private const int pageSize = 5;
        private const int productsPageSize = 15;

        public ProductController(IProductRepo repo, ICategoryRepo categoryRepo)
        {
            _repo = repo;
            _categoryRepo = categoryRepo;
        }

        [AllowAnonymous]
        public IActionResult Index(int? id, string sortOrder, string searchString, int pageIndex = 1)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.SearchString = searchString;

            var qry = _repo.Search(id).AsQueryable().AsNoTracking();

            if (!String.IsNullOrEmpty(searchString))
            {
                qry = qry.Where(q => q.ProductName.ToLower().Contains(searchString.ToLower())).AsQueryable();
            }

            qry = sortOrder switch
            {
                "Price descending" => qry.OrderByDescending(p => p.ProductPrice),
                _ => qry.OrderBy(p => p.ProductPrice),
            };

            var model = PagingList.Create(qry, pageSize, pageIndex);
            model.RouteValue = new RouteValueDictionary {
                { "searchString", searchString},
                { "sortOrder", sortOrder}
            };
            return View(model);
        }

        [AllowAnonymous]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var product = _repo.GetOne(id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        public IActionResult Create()
        {
            ViewBag.categories = new SelectList(_categoryRepo.GetAll(), "Id", "CategoryName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("ProductName,ProductPrice,ProductDescription,CategoryId")] Product product, IFormFile image)
        {
            try
            {
                product.ProductImage = ImageConvertor.ConvetrImageToByteArray(image);
                _repo.Add(product);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $@"Unable to create record: {ex.Message}");
                ViewBag.categories = new SelectList(_categoryRepo.GetAll(), "Id", "CategoryName");
                return View(product);
            }
            return RedirectToAction(nameof(ProductList));
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var inventory = _repo.GetOne(id);
            if (inventory == null)
            {
                return NotFound();
            }
            ViewBag.categories = new SelectList(_categoryRepo.GetAll(), "Id", "CategoryName");
            return View(inventory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Product product)
        {
            if (id != product.Id)
            {
                return BadRequest();
            }
            try
            {
                _repo.Update(product);
            }
            catch (DbUpdateConcurrencyException ex)
            {
                ModelState.AddModelError(string.Empty,
                    $@"Unable to save the record. Another user has updated it. {ex.Message}");
                return View(product);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $@"Unable to save the record. {ex.Message}");
                return View(product);
            }
            return RedirectToAction(nameof(ProductList));
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var inventory = _repo.GetOne(id);
            if (inventory == null)
            {
                return NotFound();
            }

            return View(inventory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete([Bind("Id,Timestamp")] Product product)
        {
            try
            {
                _repo.Delete(product);
            }
            catch (DbUpdateConcurrencyException ex)
            {
                ModelState.AddModelError(string.Empty,
                    $@"Unable to delete record. Another user updated the record. {ex.Message}");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $@"Unable to create record: {ex.Message}");
            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult ProductList(int pageIndex = 1)
        {
            var qry = _repo.GetAll().AsQueryable().AsNoTracking().OrderBy(p => p.ProductName);
            var model = PagingList.Create(qry, productsPageSize, pageIndex);

            ViewBag.categories = new SelectList(_categoryRepo.GetAll(), "Id", "CategoryName");
            model.Action = nameof(ProductList);
            return View(model);
        }
    }
}

DigitalStore.WebUI/Controllers/ProductOrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNet.Identity;
using DigitalStore.Repos.Interfaces;
using ReflectionIT.Mvc.Paging;
using DigitalStore.BusinessLogic.Interfaces;
using Microsoft.AspNetCore.Authorization;
using System.Data.Entity;
using Microsoft.AspNetCore.Mvc.Rendering;
using DigitalStore.Models;
using System.Data.Entity.Infrastructure;

namespace DigitalStore.WebUI.Controllers
{
    [Authorize("AdminAccess")]
    public class ProductOrderController : Controller
    {
        private readonly IProductOrderRepo _productOrderRepo;
        private readonly ICustomerRepo _customerRepo;
        private readonly IOrderRepo _orderRepo;
        private readonly IProductOrderLogic _productOrderLogic;
        private readonly IProductRepo _productRepo;
        private const int _categoriesPageSize = 10;
        private const int _productOrderPageSize = 15;

        public ProductOrderController(ICustomerRepo customerRepo, IOrderRepo orderRepo, 
            IProductOrderRepo productOrderRepo,
            IProductOrderLogic productOrderLogic,
            IProductRepo productRepo)
        {
            _customerRepo = customerRepo;
            _orderRepo = orderRepo;
            _productOrderRepo = productOrderRepo;
            _productOrderLogic = productOrderLogic;
            _productRepo = productRepo;
        }
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult UserOrderList(int pageIndex = 1)
        {
            var userId = User.Identity.GetUserId();
            var customers = _customerRepo.GetCustomerIdByUserId(userId);

            var productOrders = _productOrderLogic.GetOrdersOfCustomers(customers);
            ViewBag.Sum = _productOrderLogic.FindSumOfAllOrders(productOrders);

            var model = PagingList.Create(productOrders, _categoriesPageSize, pageIndex);
            model.Action = nameof(UserOrderList);
            return View(model);
        }

        public IActionResult ProductOrderList(int pageIndex = 1)
        {
            var qry = _productOrderRepo.GetRelatedData().AsQueryable().AsNoTracking().OrderBy(c => c.Id);
            var model = PagingList.Create(qry, _productOrderPageSize, pageIndex);
            model.Action = nameof(ProductOrderList);
            return View(model);
        }

        public IActionResult Edit(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }

            var customer = _productOrderRepo.GetOne(Id);
            if (customer == null)
            {
                return NotFound();
            }

            SetCustomersAndCitiesToViewBag();
            return View(customer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ProductOrder productOrder)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _productOrderRepo.Update(productOrder);
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    ModelState.AddModelError(string.Empty,
                        $@"Unable to save the record. Another user has updated it. {ex.Message}");
                    return View(productOrder);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, $@"Unable to save the record. {ex.Message}");
                    return View(productOrder);
                }
                return RedirectToAction("CustomerList");
            }
            return View(productOrder);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var customer = _productOrderRepo.GetOne(id);
            if (customer == null)
            {
                return NotFound();
            }

            SetCustomersAndCitiesToViewBag();
            return View(customer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete([Bind("Id,Timestamp")] ProductOrder productOrder)
        {
            try
            {
                _productOrderRepo.Delete(productOrder);
            }
            catch (DbUpdateConcurrencyException ex)
            {
                ModelState.AddModelError(string.Empty,
                    $@"Unable to delete record. Another user updated the record. {ex.Message}");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $@"Unable to create record: {ex.Message}");
            }
            return RedirectToAction("CustomerList");
        }

        public IActionResult Create()
        {
            SetCustomersAndCitiesToViewBag();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ProductOrder productOrder)
        {
            ModelState.Remove("Timestamp");
            if (!ModelState.IsValid) return View(productOrder);
            try
            {
                _productOrderRepo.Add(productOrder);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $@"Unable to create record: {ex.Message}");
                SetCustomersAndCitiesToViewBag();
                return View(productOrder);
            }
            return RedirectToAction("CustomerList");
        }

        private void SetCustomersAndCitiesToViewBag()
        {
            ViewBag.products = new SelectList(_productRepo.GetAll(), "Id", "ProductName");
            ViewBag.orders = new SelectList(_orderRepo.GetAll(), "Id", "OrderDate");
        }
    }
}

DigitalStore.WebUI/Views/ProductOrder/Create.cshtml
@using DigitalStore.Models
@model ProductOrder

@{
    Layout = "../Shared/_PersonLayout";
}
<div class="container p-3">
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" hidden />
        <div class="border p-3 mt-4">
            <div class="row pb-2">
                <h2 class="text-primary">Create ProductOrder</h2>
                <hr/>
            </div>
             <div class="form-group">
                   <label asp-for="Product.ProductName"></label>
                   <select asp-for="ProductId" asp-items="ViewBag.products" class ="form-control"></select>        
             </div>
             <div class="form-group">
                   <label asp-for="Order.Id"></label>
                   <select asp-for="OrderId" asp-items="ViewBag.orders" class ="form-control"></select>        
             </div>
             <br />
            <button type="submit" class="btn btn-primary" style="width:150px">
                Create
            </button>
            <a asp-controller="ProductOrder" asp-action="ProductOrderList" class="btn btn-secondary" style="width:150px">
                Back to List
            </a>
        </div>
    </form>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

DigitalStore.WebUI/Views/ProductOrder/Delete.cshtml
@using DigitalStore.Models
@model ProductOrder

@{
    Layout = "../Shared/_PersonLayout";
}

<div class="container p-3">
    <div class="row pb-2">
          <h2 class="text-primary">Delete ProductOrder</h2>
          <hr/>
    </div>
    <form method="post">
        <div class="border p-3 mt-4">
            <input type="hidden" asp-for="Timestamp"/>
            <div class="mb-3">
                <label asp-for="Id"></label>
                 <br />
                <input asp-for="Id" class="form-contorl" readonly/>
             <div class="form-group">
                   <label asp-for="Product.ProductName"></label>
                   <select asp-for="ProductId" asp-items="ViewBag.products" class ="form-control" readonly></select>        
             </div>
             <div class="form-group">
                   <label asp-for="OrderId"></label>
                   <select asp-for="OrderId" asp-items="ViewBag.orders" class ="form-control" readonly></select>        
             </div>
              <br />
            <button type="submit" class="btn btn-primary" style="width:150px">
                Delete
            </button>
            <a asp-controller="ProductOrder" asp-action="ProductOrderList" class="btn btn-secondary" style="width:150px">
                Back to List
            </a>
        </div>
    </form>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

DigitalStore.WebUI/Views/ProductOrder/Edit.cshtml
@using DigitalStore.Models
@using DigitalStore.WebUI.ExtensionClasses
@model ProductOrder

@{
    Layout = "../Shared/_PersonLayout";
}

<div class="container p-3">
    <form method="post" enctype="multipart/form-data">
        <div class="border p-3 mt-4">
            <div class="row pb-2">
                <h2 class="text-primary">Edit ProductOrder</h2>
                <hr/>
            </div>
            <input type="hidden" asp-for="Timestamp"/>
            <div class="mb-3">
                <label asp-for="Id"></label>
                <br/>
                <input asp-for="Id" class="form-contorl" readonly/>
            <div class="form-group">
                   <label asp-for="Product.ProductName"></label>
                   <select asp-for="ProductId" asp-items="ViewBag.products" class ="form-control"></select>        
             </div>
             <div class="form-group">
                   <label asp-for="OrderId"></label>
                   <select asp-for="OrderId" asp-items="ViewBag.orders" class ="form-control"></select>        
             </div>
              <br />
            <button type="submit" class="btn btn-primary" style="width:150px">
                Update
            </button>
            <a asp-controller="ProductOrder" asp-action="ProductOrderList" class="btn btn-secondary" style="width:150px">
                Back to List
            </a>
        </div>
    </form>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

DigitalStore.WebUI/Views/ProductOrder/ProductOrderList.cshtml
@using DigitalStore.Models
@using DigitalStore.WebUI.ExtensionClasses
@using ReflectionIT.Mvc.Paging
@model ReflectionIT.Mvc.Paging.PagingList<ProductOrder>
@addTagHelper *, ReflectionIT.Mvc.Paging

@{
    Layout = "../Shared/_PersonLayout";
}

<nav class="pagination">
    <vc:pager paging-list="@Model"/>
</nav>

<div class="container p-3">
<table class="table table-bordered table-striped" style="width:100%">
	<div class="col-12 text-end">
			<a asp-controller="ProductOrder" asp-action="Create" class="btn btn-primary" style="width:100px">
				<i class="bi bi-plus-square"></i> &nbsp; Create
			</a>
	</div>
	<thead>
		<tr>
			<th>
				Id
			</th>
			<th>
				Product Name
			</th>
			<th>
				Product Price
			</th>
			<th>
				Order Date
			</th>
			<th>
				City Name
			</th>
			<th>
				Last Name
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var obj in Model)
		{
			<tr>
				<td width="10%">
					@obj.Id
				</td>
				<td width="10%">
					@obj.Product.ProductName
				</td>
				<td width="10%">
					@obj.Product.ProductPrice $
				</td>
				<td width="10%">
					@obj.Order.OrderDate
				</td>
				<td width="10%">
					@obj.Order.City.CityName
				</td>
				<td width="10%">
					@obj.Order.Customer.LastName
				</td>
				<td>
					<div class="w-100 btn-group" role="group">
						<a asp-controller="ProductOrder" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2" style="width:50px">
							<i class="bi bi-pencil"></i>Edit</a>
							<a asp-controller="ProductOrder" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2" style="width:50px">
							Delete</a>
					</div>
				</td>
			</tr>
		}
	</tbody>
</table>
</div>

<nav class="pagination">
    <vc:pager paging-list="@Model"/>
</nav>

DigitalStore.WebUI/Views/ProductOrder/UserOrderList.cshtml
@using DigitalStore.Models
@using DigitalStore.WebUI.ExtensionClasses
@using ReflectionIT.Mvc.Paging
@model ReflectionIT.Mvc.Paging.PagingList<ProductOrder>
@addTagHelper *, ReflectionIT.Mvc.Paging

<nav class="pagination">
    <vc:pager paging-list="@Model"/>
</nav>

<div class="container p-3">
<table class="table table-bordered table-striped" style="width:100%">
	<div class="col-12 text-end">
			@*<a asp-controller="Product" asp-action="Create" class="btn btn-primary" style="width:100px">
				<i class="bi bi-plus-square"></i> &nbsp; Create
			</a>*@
			Amount: @ViewBag.Sum $
	</div>
	<thead>
		<tr>
			<th>
				Number
			</th>
			<th>
				Customer FirstName
			</th>
			<th>
				Customer MidName
			</th>
			<th>
				Customer Phonenumber
			</th>
			<th>
				Product Category
			</th>
			<th>
				Product Name
			</th>
			<th>
				Product Price
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@{
			int counter = 0;
		}
		@foreach (var obj in Model)
		{
			counter++;
			<tr>
				<td width="5%">
					@counter
				</td>
				<td width="15%">
					@obj.Order.Customer.FirstName
				</td>
				<td width="15%">
					@obj.Order.Customer.MidName
				</td>
				<td width="10%">
					@obj.Order.Customer.PhoneNumber
				</td>
				<td width="10%">
					@obj.Product.Category.CategoryName
				</td>
				<td width="15%">
					@obj.Product.ProductName
				</td>
				<td width="10%">
					@obj.Product.ProductPrice $
				</td>
			</tr>
		}
	</tbody>
</table>
</div>

<nav class="pagination">
    <vc:pager paging-list="@Model"/>
</nav>